### ISSUE TITLE
importing the manager

### ISSUE THREAD

**Issue by marcogamaliel** [slashinfty/tournament-organizer#12]
Hi guys!
I've problems importing the library, because my project doesn't recognize the types.
I'm using typescript "4.5.4" and node "v16.14.0"
I get typos error and the my project doesn't run if I tried import it this way:
`
import TournamentManager from 'tournament-organizer'
`
I found a way to use it and run, but doesn't detect the types:
`const TournamentManager = require('tournament-organizer')`
`const manager = new TournamentManager.default()`
or if I change in your package.json

`-- "types": "./dist/index.d.js",`
`++ "types": "./dist/esm/index.d.js",`

It run and detect the types correctly using:
`
import TournamentManager from 'tournament-organizer'
`
am I missing some configuration or something?

pd: "./dist/index.d.js" doest't exist

Thanks for the help

**Comment by slashinfty** [comment]
Ah, thanks for pointing that out. I'll ship out an update momentarily.

**Comment by slashinfty** [comment]
Fixed with [v2.2.2](https://github.com/slashinfty/tournament-organizer/commit/5515ace43e5c9fa30614a2f9126ab9cd5461fab8)

**Comment by marcogamaliel** [comment]
thanks for the help, the update works!
