### ISSUE TITLE
Minimum of 8 players for Swiss?

### ISSUE THREAD

**Issue by AndreasSG** [slashinfty/tournament-organizer#13]
I just want to know why there is a limit of a minimum of 8 players when creating a Swiss tournament?

I haven't been able to find any documentation or source for why this number could be chosen, so if you have a reason for this then please let me know. All i find when looking at implementations of this tournament mode for chess, magic, or others is that there is no minimum player count. They usually just restrict the number of rounds instead.

Maybe this limit could be a parameter that you should be able to set yourself when creating the Swiss tournament?

**Comment by slashinfty** [comment]
I'm out of town until Thursday. If you'd like to open up a pull request where the minimum number of players is 2 instead of 8, I'd be happy to do that. If you are unable to do a pull request, I will do so when I return home.

**Comment by slashinfty** [comment]
Addressed in #14

**Comment by slashinfty** [comment]
@AndreasSG  v2.3.0 has been published to npm, and this fix is included (in addition to lowering the round-robin and elimination player minimum to 2).
