### ISSUE TITLE
Single Elimination with 3 players enrolled will crash

### ISSUE THREAD

**Issue by sirtobey** [slashinfty/tournament-organizer#16]
Hey @slashinfty 

I am currently experimenting with your library - I really like it! Thanks for building it.
When using it I encountered a bug, though.

```js
      const manager = new TournamentOrganizer();
      const tournament = manager.newTournament({
        format: "elimination",
        double: false,
      });

      tournament.addPlayer({ alias: "Team1" });
      tournament.addPlayer({ alias: "Team2" });
      tournament.addPlayer({ alias: "Team3" });
      tournament.startEvent();
```

This will produce an error:

```
[2022-11-16 09:47:55.363] error: Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
    at /Users/user/projects/project/node_modules/tournament-organizer/dist/cjs/Pairings.js:112:59
    at Array.forEach (<anonymous>)
    at Object.singleElimination (/Users/user/projects/project/node_modules/tournament-organizer/dist/cjs/Pairings.js:109:71)
    at Elimination.startEvent (/Users/user/projects/project/node_modules/tournament-organizer/dist/cjs/Tournament.js:999:22)
[...]
```

After a quick dive into the code the issue seems to be, that the bracket distribution `const bracket = [1, 4, 2, 3]` of course doesn't account for less than 4 players.

I have not yet had the chance to dive deeper into the code, but as single elimination tournaments don't really make sense for less than 4 players, I will implement a safe guard for this condition. Perhaps changing the required amount of players to 4 for elimination brackets might also be a quickfix.

If you'd like to point me in a direction I'll gladly do a PR, too. 

Thanks!

**Comment by slashinfty** [comment]
It would just be updating [these couple lines](https://github.com/slashinfty/tournament-organizer/blob/main/src/Tournament.ts#L1389-L1391). Feel free to make the PR and I'll push things tonight.

FYI - I'm working on v3, which will be quite an overhaul. However, I have limited time to work on these hobby projects, so I have no timetable for that.

**Comment by slashinfty** [comment]
Update: it's actually more than just that. These two lines ([this](https://github.com/slashinfty/tournament-organizer/blob/main/src/Pairings.ts#L32) and [this](https://github.com/slashinfty/tournament-organizer/blob/main/src/Pairings.ts#L151)) need to be changed to `const bracket = exponent < 2 ? [1, 2] : [1, 4, 2, 3];`

Aside: v3 might actually be done relatively soon. I've had some free time lately.

**Comment by slashinfty** [comment]
Fixed with [v2.3.2](https://github.com/slashinfty/tournament-organizer/commit/a44aaf8e8925bec4ad06caf5b1621339528eb4f4)

**Comment by sirtobey** [comment]
Oh, wow! Thanks so much! I disabled all mails because I got too much spam from work, haven't worked on my hobby project since then and dropped in to look at the status - and apparently you're already done! 🚀 

Maybe I can take a deeper look at this lib and help you out when I find the time?

**Comment by slashinfty** [comment]
You're welcome to. I did just release v3.0 Friday night, which is a complete reworking (I think it's far simpler now).

**Comment by sirtobey** [comment]
I need to check it out - I am working with Strapi, which unfortunately won't be moved to ESM anytime soon... It works with dynamic imports, however it breaks when using TS <4.7 (or 4.8, not sure), as this will always transpile a dynamic `import()` to ESM. TS 4.7 should fix this issue by allowing to respect modules. 

But that's just a side note.

Thanks for your work, enjoy your Kofi, and I'll keep watching this library! 🤝
