### ISSUE TITLE
Is there a way to know what matches are from the upper or low bracket?

### ISSUE THREAD

**Issue by Ceneka** [slashinfty/tournament-organizer#17]

**Comment by slashinfty** [comment]
I assume you mean winner's and loser's brackets in double elimination? That code resides in the [tournament-pairings package](https://github.com/slashinfty/tournament-pairings/blob/main/src/DoubleElimination.ts). It creates all winner's rounds, then places the loser's rounds after them. You can identify the first round containing loser's matches by looking at the loser's path in the first round matches.

**Comment by Ceneka** [comment]
Yeah, that's exactly what I was talking about! thanks
