### ISSUE TITLE
Create groups with players

### ISSUE THREAD

**Issue by ricardo17coelho** [slashinfty/tournament-organizer#21]
Hi 👋

It's possible to create groups and assign players to groups ?
Ex:
- StageOne: 4 Groups, where the best 2 go to the stageTwo
- StageTwo: `single-elimination` or `double-elimination` with the best 2 players from stageOne (across multiple groups)

I'm trying to do something like:
![Screenshot 2023-10-26 at 00 13 16](https://github.com/slashinfty/tournament-organizer/assets/37732431/bb77cd5c-9ca7-42f3-bd2e-491da7152b49)

Thx 🙏

**Comment by slashinfty** [comment]
This sounds like it can all be accomplished on the backend of the implementation.

Each group is essentially it's own tournament. When it's complete, you can take the top two players from `tournament.standings()` and add them to a new tournament.

If you want to be able to preserve player history, you can copy all of the values of the player from the old tournament into the player in the new tournament. However, there would be an issue with round numbers. So, what I can do is add a setting so the first round of a tournament can be an arbitrary number. If your group stage is running 3 rounds, you can start a new single elimination tournament with the first round being 4. Thus, match history won't get screwed up.

Thoughts?

**Comment by ricardo17coelho** [comment]
Yes this can be an good idea 👍
Thx 🙏

**Comment by slashinfty** [comment]
I'll add this to 3.4.0, which will come in the near future (might be more changes based on #20)

**Comment by slashinfty** [comment]
`stageOne.initialRound` now added in [v3.4.0](https://github.com/slashinfty/tournament-organizer/commit/30e26f82e0e522e76ed379da26133f02980c642d)
