### ISSUE TITLE
Groups support

### ISSUE THREAD

**Issue by omikulcik** [slashinfty/tournament-organizer#23]
Hi @slashinfty and thank you again for this library. It has helped me tremendously during my project. 

What I am trying to achieve now is a tournament with groups where in each group each player would be matched agains other players from his group. Then I need to set how many players advance from each group and pair them into next groups round the way that players that have already played with each other in the previous group are not matched again if possible.

I do not think there is currently a way of achieving this through this library but maybe round-robin could be tweaked. Please, have you considered adding this tournament-system? If I tried to implement this system myself would you be interested to add it into this library? I could submit a PR.

Thank you :)

**Comment by slashinfty** [comment]
Hey! Thanks for the kind words, and I am glad this library has been useful.

My goal with the library is to keep functionality relatively basic at its core. I do not intend on adding group support. I believe this is easily done by any implementation of the library.

Each group can be ran as a separate tournament in the manager, and then based on however many players would advance and the number of groups desired, you can create additional tournaments and add the players in such a way to minimize replaying. If you want to preserve prior matches for statistics, you can use `player.values` with previous instances.
