### ISSUE TITLE
Handling tournament with database

### ISSUE THREAD

**Issue by pedrohba1** [slashinfty/tournament-organizer#6]
I have a use case where I want to handle a tournament and save it's state on a database, be it mongo or sql.
Is there a possible approach for it using this module or would it require a lot of additional features?

I'm thinking about instantiating an object of a tournament and saving it as a blob on the database, but there could also be something better.

**Comment by pedrohba1** [comment]
It can work with objects, however I would like to make it work in a back-end. Thing is, the back-end might go down and the class instance would be gone with it. I would like to have a way to save it somehow. 

I would gladly add this feature if you are ok. Do you have any development guide on this project?

**Comment by slashinfty** [comment]
Sorry I haven't responded. If you want to officially contribute, please feel free to make a pull request. No worries if you aren't able to.

**Comment by pedrohba1** [comment]
All right. I will, in some time. I have no time right now to add the types the correct way. The original database issue was solved. I will mark this as solved.
