### ISSUE TITLE
create blank match for all round???

### ISSUE THREAD

**Issue by jonfrusciante** [slashinfty/tournament-organizer#7]
hello, in the meantime, congratulations on your excellent work.
Would it be possible to create all maches in eliminator mode and even those that are not to be played or finished in each round when a perfect game is not created ???
example when you create a 10-person tournament elim the first round is done by only 2 matches instead it should be done by 8, 2 with teams and the others with teams that have already passed to round 2 in the right positions.

**Comment by slashinfty** [comment]
It is designed to replicate Challonge brackets (image attached
![21-11-05_19:19:08](https://user-images.githubusercontent.com/14860235/140588561-a54547b0-9776-4f1d-9646-7130e27e11c1.png)
).
